In [188]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [189]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [190]:
df.shape

(569, 33)

In [191]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [192]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train test split

In [193]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [194]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [195]:
X_train

array([[-0.76780091, -0.45764851, -0.7560567 , ..., -0.75963084,
        -0.50236885, -0.15641517],
       [-1.10360232, -1.08409278, -1.06683467, ..., -1.1121358 ,
        -0.74096451,  0.05138498],
       [ 0.91407622,  0.70368278,  0.94114095, ...,  0.58467285,
         0.26590919, -0.48083786],
       ...,
       [-0.50662204,  1.84332946, -0.44402896, ...,  0.48019329,
         0.50132357,  1.93960987],
       [ 2.34338477,  0.11097013,  2.54085597, ...,  2.67729249,
         1.83745928,  0.74104826],
       [-0.71900925,  1.27230142, -0.73231093, ..., -0.99993384,
         0.54745207, -0.87258356]], shape=(455, 30))

In [196]:
y_train

142    B
345    B
262    M
563    M
553    B
      ..
92     B
362    B
193    M
108    M
305    B
Name: diagnosis, Length: 455, dtype: str

### Label encoding

In [197]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [198]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0])

### Numpy arrays to PyTorch tensors

In [199]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [200]:
X_train_tensor.shape

torch.Size([455, 30])

In [201]:
X_train_tensor

tensor([[-0.7678, -0.4576, -0.7561,  ..., -0.7596, -0.5024, -0.1564],
        [-1.1036, -1.0841, -1.0668,  ..., -1.1121, -0.7410,  0.0514],
        [ 0.9141,  0.7037,  0.9411,  ...,  0.5847,  0.2659, -0.4808],
        ...,
        [-0.5066,  1.8433, -0.4440,  ...,  0.4802,  0.5013,  1.9396],
        [ 2.3434,  0.1110,  2.5409,  ...,  2.6773,  1.8375,  0.7410],
        [-0.7190,  1.2723, -0.7323,  ..., -0.9999,  0.5475, -0.8726]])

### Define the model

In [202]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

### Improtant parameters

In [203]:
learning_rate = 0.1
epochs = 25

In [204]:
loss_function = nn.BCELoss()

### Trainning Pipeline

In [205]:
# Create a model
model = MySimpleNN(X_train_tensor.shape[1])

In [206]:
# Define an optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [207]:
#define loop
for epoch in range(epochs):
    
    # Forward pass
    y_pred = model(X_train_tensor)

    # Loss calculation
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # Clear gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Parameter update
    optimizer.step()

    # Print loss in each epoch
    print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 0.8490069508552551
Epoch: 2, loss: 0.6075315475463867
Epoch: 3, loss: 0.48484325408935547
Epoch: 4, loss: 0.4156789481639862
Epoch: 5, loss: 0.3707050681114197
Epoch: 6, loss: 0.3385552167892456
Epoch: 7, loss: 0.31410109996795654
Epoch: 8, loss: 0.2946840524673462
Epoch: 9, loss: 0.27877721190452576
Epoch: 10, loss: 0.26543402671813965
Epoch: 11, loss: 0.25403255224227905
Epoch: 12, loss: 0.24414482712745667
Epoch: 13, loss: 0.23546525835990906
Epoch: 14, loss: 0.22776877880096436
Epoch: 15, loss: 0.22088545560836792
Epoch: 16, loss: 0.21468403935432434
Epoch: 17, loss: 0.20906123518943787
Epoch: 18, loss: 0.20393452048301697
Epoch: 19, loss: 0.19923695921897888
Epoch: 20, loss: 0.19491352140903473
Epoch: 21, loss: 0.19091859459877014
Epoch: 22, loss: 0.18721383810043335
Epoch: 23, loss: 0.1837669014930725
Epoch: 24, loss: 0.18055014312267303
Epoch: 25, loss: 0.17753984034061432

In [208]:
model.linear.weight

Parameter containing:
tensor([[ 0.2130,  0.1066,  0.3561,  0.1056, -0.0307,  0.2048,  0.1706,  0.1935,
          0.1755,  0.0137,  0.0691,  0.0441,  0.0778,  0.1658,  0.0788, -0.0330,
          0.0096,  0.0255, -0.0890, -0.1016,  0.4619,  0.2454,  0.1636,  0.3647,
         -0.0136,  0.2139,  0.1587,  0.3049,  0.1823,  0.1623]],
       requires_grad=True)

### Evaluation

In [209]:
# Model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5624807476997375