In [78]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [80]:
df.shape

(569, 33)

In [81]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [82]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train test split

In [83]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [84]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [85]:
X_train

array([[ 0.41221651,  3.39033849,  0.49769061, ...,  1.32701665,
         0.99985778,  2.00976283],
       [-0.63493423, -1.07958367, -0.60279845, ..., -0.1012102 ,
        -0.48037529,  0.83246872],
       [-0.59901613,  0.54304308, -0.58190563, ..., -0.37105264,
        -0.96780887,  0.87223849],
       ...,
       [-1.31793071, -1.51070494, -1.19824379, ..., -0.14742631,
         0.22713699,  2.27126268],
       [-0.02708947, -1.439641  , -0.04029948, ..., -0.16233473,
        -1.2041897 , -0.59815336],
       [-0.82833938, -1.02273252, -0.82940518, ..., -0.66862475,
         0.49449186, -0.57963046]], shape=(455, 30))

In [86]:
y_train

259    M
510    B
450    B
84     B
120    B
      ..
217    B
295    B
504    B
528    B
381    B
Name: diagnosis, Length: 455, dtype: str

### Label encoding

In [87]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [88]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### Numpy arrays to PyTorch tensors

In [89]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [90]:
X_train_tensor.shape

torch.Size([455, 30])

In [91]:
X_train_tensor

tensor([[ 0.4122,  3.3903,  0.4977,  ...,  1.3270,  0.9999,  2.0098],
        [-0.6349, -1.0796, -0.6028,  ..., -0.1012, -0.4804,  0.8325],
        [-0.5990,  0.5430, -0.5819,  ..., -0.3711, -0.9678,  0.8722],
        ...,
        [-1.3179, -1.5107, -1.1982,  ..., -0.1474,  0.2271,  2.2713],
        [-0.0271, -1.4396, -0.0403,  ..., -0.1623, -1.2042, -0.5982],
        [-0.8283, -1.0227, -0.8294,  ..., -0.6686,  0.4945, -0.5796]],
       dtype=torch.float64)

### Define the model

In [92]:
class MySimpleNN():

    def __init__(self, X):
        self.weights = torch.randn(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Improtant parameters

In [93]:
learning_rate = 0.1
epochs = 25

### Trainning Pipeline

In [94]:
# Create a model
model = MySimpleNN(X_train_tensor)
model.weights

tensor([[ 0.9456],
        [-1.8512],
        [-1.4693],
        [ 0.6563],
        [-0.8778],
        [-1.5237],
        [-1.8938],
        [ 0.4075],
        [-1.3825],
        [-1.4060],
        [ 0.6671],
        [ 0.2947],
        [ 0.5146],
        [-0.2587],
        [-2.5187],
        [ 2.3988],
        [ 0.4363],
        [ 1.9186],
        [-0.0948],
        [ 0.4820],
        [-0.9783],
        [-2.1647],
        [-1.1801],
        [-0.6358],
        [ 0.6024],
        [ 0.3470],
        [ 1.0125],
        [ 0.7306],
        [ 1.1447],
        [-1.0425]], dtype=torch.float64, requires_grad=True)

In [95]:
#define loop
for epoch in range(epochs):
    
    # Forward pass
    y_pred = model.forward(X_train_tensor)

    # Loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward pass
    loss.backward()

    # Parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print loss in each epoch
    print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 2.2559536473666078
Epoch: 2, loss: 2.1976471639611757
Epoch: 3, loss: 2.1449347201176376
Epoch: 4, loss: 2.0974588065168396
Epoch: 5, loss: 2.054699405775138
Epoch: 6, loss: 2.0160807936006933
Epoch: 7, loss: 1.9809937303770173
Epoch: 8, loss: 1.9485794050176795
Epoch: 9, loss: 1.9188555560219813
Epoch: 10, loss: 1.8914118686701065
Epoch: 11, loss: 1.8658885699035728
Epoch: 12, loss: 1.841980784726429
Epoch: 13, loss: 1.8194365414397533
Epoch: 14, loss: 1.7980501813327203
Epoch: 15, loss: 1.7776544685532205
Epoch: 16, loss: 1.7581133263700002
Epoch: 17, loss: 1.7393157763771563
Epoch: 18, loss: 1.7211710436647856
Epoch: 19, loss: 1.7036046336794817
Epoch: 20, loss: 1.6865551902024427
Epoch: 21, loss: 1.6699719787301348
Epoch: 22, loss: 1.6538128707291437
Epoch: 23, loss: 1.6380427283362036
Epoch: 24, loss: 1.6226170881367608
Epoch: 25, loss: 1.6072365270514504

In [96]:
model.bias

tensor([-0.3236], dtype=torch.float64, requires_grad=True)

### Evaluation

In [98]:
# Model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5338565707206726